baseurl = "/"
languageCode = "en-us"
title = "Test page"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "Blas Gomez"
    email = "jblas1989@gmail.com"
    github = "blgo"
    linkedin = "blas-gomez-49080155"
    facebook = "blasgf"
    gaID = "YOUR Google Analytics Tracking ID"
    twitter = "JBlasGomez"
