baseurl = "/"
languageCode = "en"
title = "Test page"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2017; all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "Blas Gomez"
    email = "jblas1989@gmail.com"
    github = "blgo"
    linkedin = "blas-gomez-49080155"
    facebook = "blasgf"
    gaID = "YOUR Google Analytics Tracking ID"
    twitter = "JBlasGomez"

DefaultContentLanguage = "en"

[params.navigation]
help  = "Help"

[Languages]
[Languages.en]
title = "My test page"
weight = 1
[Languages.en.params]
linkedin = "english-link"

[Languages.es]
copyright = "Copyright (c) 2017; Todos los derechos reservados."
title = "Mi pagina de pruebas"
weight = 2
[Languages.es.params]
linkedin = "Enlace en espanol"
[Languages.es.navigation]
help  = "Ayuda"
